name: Secure Extract and Encrypt
on:
  repository_dispatch:
    types: [unzip-and-encrypt-event]
permissions:
  contents: write

jobs:
  secure-process-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Recreate ZIP file
        run: |
          echo "${{ github.event.client_payload.zip_data }}" | base64 --decode > temporary.zip
      - name: Unzip archive
        run: |
          unzip temporary.zip -d ./extracted-tmp
      - name: Encrypt files with GPG
        env:
          PASSPHRASE: ${{ github.event.client_payload.crypto_key }}
          DIR_NAME: "run-${{ github.run_id }}"
        run: |
          mkdir -p "./posts/$DIR_NAME" #
          for file in ./extracted-tmp/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              gpg --batch --yes --passphrase "$PASSPHRASE" --symmetric --cipher-algo AES256 -o "./posts/$DIR_NAME/${filename}.gpg" "$file"
            fi
          done
      - name: "Update or create filelist.json.gpg"
        env:
          PASSPHRASE: ${{ github.event.client_payload.filelist_key }}
          DIR_NAME: "run-${{ github.run_id }}"
          HINT: ${{ github.event.client_payload.crypto_hint }}
          TITLE: ${{ github.event.client_payload.title }}
        run: |
          if [ -f "./posts/filelist.json.gpg" ]; then
            gpg --batch --yes --passphrase "$PASSPHRASE" --decrypt -o filelist.json ./posts/filelist.json.gpg
          else
            echo "[]" > filelist.json
          fi
          jq --arg dir "$DIR_NAME" --arg hint "$HINT" --arg title "$TITLE" '. += [{"dir": $dir, "hint": $hint, "title": $title}]' filelist.json > tmp.json && mv tmp.json filelist.json
          gpg --batch --yes --passphrase "$PASSPHRASE" --symmetric --cipher-algo AES256 -o "./posts/filelist.json.gpg" filelist.json
      - name: Clean up raw data
        run: |
          rm -rf temporary.zip ./extracted-tmp
          rm -f filelist.json
      - name: Commit and push encrypted files only
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./posts/**/*.gpg ./posts/filelist.json.gpg
          git diff --staged --quiet || (git commit -m "Chore: ユーザー指定パスワードで自動暗号化されたファイルを追加" && git push)
