name: Secure Extract and Encrypt
on:
  push:
    branches:
      - data-transport
permissions:
  contents: write

jobs:
  secure-process-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Prepare main branch files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@github.com"
          git fetch origin main
          git checkout origin/main -- posts/ || true
      - name: Unzip archive
        run: |
          unzip upload.zip -d ./extracted-tmp
      - name: Encrypt files with GPG
        run: |
          PASSPHRASE=$(jq -r '.crypto_key' config.json)
          DIR_NAME="run-${{ github.run_id }}"
          mkdir -p "./posts/$DIR_NAME" #
          for file in ./extracted-tmp/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              gpg --batch --yes --passphrase "$PASSPHRASE" --symmetric --cipher-algo AES256 -o "./posts/$DIR_NAME/${filename}.gpg" "$file"
            fi
          done
      - name: "Update or create filelist.json.gpg"
        run: |
          PASSPHRASE=$(jq -r '.filelist_key' config.json)
          HINT=$(jq -r '.crypto_hint' config.json)
          TITLE=$(jq -r '.title' config.json)
          DIR_NAME="run-${{ github.run_id }}"
          if [ -f "./posts/filelist.json.gpg" ]; then
            gpg --batch --yes --passphrase "$PASSPHRASE" --decrypt -o filelist.json ./posts/filelist.json.gpg
          else
            echo "[]" > filelist.json
          fi
          jq --arg dir "$DIR_NAME" --arg hint "$HINT" --arg title "$TITLE" '. += [{"dir": $dir, "hint": $hint, "title": $title}]' filelist.json > tmp.json && mv tmp.json filelist.json
          gpg --batch --yes --passphrase "$PASSPHRASE" --symmetric --cipher-algo AES256 -o "./posts/filelist.json.gpg" filelist.json
      - name: Commit and push to main branch
        run: |
          git checkout -B main origin/main
          git add ./posts/**/*.gpg ./posts/filelist.json.gpg
          git diff --staged --quiet || (git commit -m "Chore: 大容量ファイルを暗号化して追加" && git push origin main)
      - name: Clean up raw data from transport branch
        run: |
          git checkout data-transport
          rm -rf upload.zip ./extracted-tmp filelist.json tmp.json
          echo "This branch is used for temporary data transport." > README.md
          git add -A
          git commit --amend -m "Chore: 生データの完全消去"
          git push origin data-transport --force
